apiVersion: v1
kind: ConfigMap
metadata:
  name: agent
  labels:
    app: agent
data:
  Corefile: |
    .:53 {
        errors
        health
        route42
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: v1
kind: Service
metadata:
  name: agent
  labels:
    app: agent
spec:
  ports:
  - port: 53
    protocol: UDP
    targetPort: 53
  selector:
    app: agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  replicas: 1
  template:
    metadata:
      labels:
        app: agent
    spec:
      volumes:
      - name: config
        configMap:
          name: agent
      dnsPolicy: Default
      containers:
      - args:
        - -conf=/config/Corefile
        image: quay.io/nschieder/coredns:v1.6.5-route42
        imagePullPolicy: IfNotPresent
        name: agent
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successTheshold: 1
          timeoutSeconds: 1
        env:
        - name: ROUTE42_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
