apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# default namespace
namespace: route42-system
namePrefix: route42-
resources:
- agent.yaml
commonLabels:
  app.kubernetes.io/name: agent
  app.kubernetes.io/component: dns-server
  app.kubernetes.io/part-of: route42
