apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-role
rules:
- apiGroups:
  - route42.thetechnick.ninja
  resources:
  - recordsets
  - zones
  verbs:
  - get
  - list
  - watch
